spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-public
          uri: http://AUTHORIZATIONSERVICE:8081/
          predicates:
            - Path=/api/auth/**
            
        - id: auth-service-protected
          uri: http://AUTHORIZATIONSERVICE:8081/
          predicates:
            - Path=/api/account/**, /api/permission/category/**, /api/permission/**, /api/role/**, /api/role-permission/**
            - Header=Authorization, Bearer .*
          filters:
            - name: AuthenticationFilter

        - id: user-service
          uri: http://USERSERVICE:8082/
          predicates:
            - Path=/api/user/**
          filters:
            - name: AuthenticationFilter
            
        - id: video-service
          uri: http://VIDEOSERVICE:8083/
          predicates:
            - Path=/api/video/**
          filters:
            - name: AuthenticationFilter
            
        - id: image-service
          uri: https://image.vothanhtuyen.id.vn
          predicates:
            - Path=/api/image/**
          filters:
            - name: AuthenticationFilter
            
        - id: music-service
          uri: http://MUSICSERVICE:5221/
          predicates:
            - Path=/api/music/**
          filters:
            - name: AuthenticationFilter
            
        - id: payment-service
          uri: http://PAYMENTSERVICE:5000/
          predicates:
            - Path=/api/payment/**
          filters:
            - name: AuthenticationFilter
            
        - id: censorship-service
          uri: http://CENSORSHIPSERVICE
          predicates:
            - Path=/api/censorship/**
            
        - id: notification-service
          uri: http://NOTIFICATIONSERVICE:5050/
          predicates:
            - Path=/api/notification/**
            
      discovery:
        locator:
            enabled: true
            lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URI}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET_KEY}
