spring:
  cloud:
    gateway:
      routes:
        - id: auth-service-public
          uri: http://c3930cd0ddc9:8081
          predicates:
            - Path=/api/auth/**
            
        - id: auth-service-protected
          uri: lb://AUTHORIZATIONSERVICE
          predicates:
            - Path=/api/account/**, /api/permission/category/**, /api/permission/**, /api/role/**, /api/role-permission/**
            - Header=Authorization, Bearer .*
          filters:
            - name: AuthenticationFilter

        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/user/**
          filters:
            - name: AuthenticationFilter
            
        - id: video-service
          uri: lb://VIDEOSERVICE
          predicates:
            - Path=/api/video/**
          filters:
            - name: AuthenticationFilter
            
        - id: image-service
          uri: lb://IMAGESERVICE
          predicates:
            - Path=/api/image/**
          filters:
            - name: AuthenticationFilter
            
        - id: music-service
          uri: lb://MUSICSERVICE
          predicates:
            - Path=/api/music/**
          filters:
            - name: AuthenticationFilter
            
        - id: payment-service
          uri: lb://PAYMENTSERVICE
          predicates:
            - Path=/api/payment/**
          filters:
            - name: AuthenticationFilter
            
        - id: censorship-service
          uri: lb://CENSORSHIPSERVICE
          predicates:
            - Path=/api/censorship/**
            
        - id: notification-service
          uri: lb://NOTIFICATIONSERVICE
          predicates:
            - Path=/api/notification/**
            
      discovery:
        locator:
            enabled: true
            lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URI}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET_KEY}
