spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AuthorizationService
          predicates:
            - Path=/api/auth/**, /api/permission/category/**, /api/permission/**, /api/role/**, /api/role-permission/**
            - Path=/api/account/**
          filters:
            - AuthenticationFilter
        - id: user-service
          uri: lb://UserService
          predicates:
            - Path=/api/user/**
          filters:
            - AuthenticationFilter
        - id: video-service
          uri: lb://VideoService
          predicates:
            - Path=/api/video/**
          filters:
            - AuthenticationFilter
        - id: image-service
          uri: lb://ImageService
          predicates:
            - Path=/api/image/**
          filters:
            - AuthenticationFilter
        - id: music-service
          uri: lb://MusicService
          predicates:
            - Path=/api/music/**
          filters:
            - AuthenticationFilter
        - id: payment-service
          uri: lb://PaymentService
          predicates:
            - Path=/api/payment/**
          filters:
            - AuthenticationFilter
        - id: censorship-service
          uri: lb://CensorshipService
          predicates:
            - Path=/api/censorship/**
        - id: notification-service
          uri: lb://NotificationService
          predicates:
            - Path=/api/notification/**
      discovery:
        locator:
            enabled: true
            lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URI}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET_KEY}
