eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URI}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET_KEY}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
